# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'installer_one.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InstallerFirstStep(object):
    def setupUi(self, InstallerFirstStep):
        InstallerFirstStep.setObjectName("InstallerFirstStep")
        InstallerFirstStep.setWindowModality(QtCore.Qt.NonModal)
        InstallerFirstStep.resize(700, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(InstallerFirstStep.sizePolicy().hasHeightForWidth())
        InstallerFirstStep.setSizePolicy(sizePolicy)
        InstallerFirstStep.setMinimumSize(QtCore.QSize(700, 500))
        InstallerFirstStep.setMaximumSize(QtCore.QSize(700, 500))
        font = QtGui.QFont()
        font.setPointSize(13)
        InstallerFirstStep.setFont(font)
        InstallerFirstStep.setStyleSheet("")
        self.switcher = QtWidgets.QStackedWidget(InstallerFirstStep)
        self.switcher.setGeometry(QtCore.QRect(0, 0, 700, 500))
        self.switcher.setMinimumSize(QtCore.QSize(700, 500))
        self.switcher.setMaximumSize(QtCore.QSize(700, 500))
        self.switcher.setObjectName("switcher")
        self.page = QtWidgets.QWidget()
        self.page.setMinimumSize(QtCore.QSize(700, 500))
        self.page.setMaximumSize(QtCore.QSize(700, 500))
        self.page.setObjectName("page")
        self.continue1 = QtWidgets.QPushButton(self.page)
        self.continue1.setGeometry(QtCore.QRect(410, 440, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Molodo-font")
        font.setPointSize(10)
        self.continue1.setFont(font)
        self.continue1.setStyleSheet("QPushButton {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding: 10px;\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: rgba(230, 230, 230, 230);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(200, 200, 200, 230);\n"
"}")
        self.continue1.setObjectName("continue1")
        self.cancle1 = QtWidgets.QPushButton(self.page)
        self.cancle1.setGeometry(QtCore.QRect(570, 440, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Molodo-font")
        font.setPointSize(10)
        self.cancle1.setFont(font)
        self.cancle1.setStyleSheet("QPushButton {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding: 10px;\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: rgba(230, 230, 230, 230);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(200, 200, 200, 230);\n"
"}")
        self.cancle1.setObjectName("cancle1")
        self.icon1 = QtWidgets.QLabel(self.page)
        self.icon1.setGeometry(QtCore.QRect(10, 400, 91, 91))
        self.icon1.setText("")
        self.icon1.setObjectName("icon1")
        self.main_text = QtWidgets.QLabel(self.page)
        self.main_text.setGeometry(QtCore.QRect(10, 20, 671, 361))
        font = QtGui.QFont()
        font.setFamily("Monomakh Unicode")
        font.setPointSize(10)
        font.setStrikeOut(False)
        self.main_text.setFont(font)
        self.main_text.setStyleSheet("QLabel {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding: 10px;\n"
"        border-radius: 20px;\n"
"    }")
        self.main_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.main_text.setWordWrap(True)
        self.main_text.setObjectName("main_text")
        self.background1 = QtWidgets.QLabel(self.page)
        self.background1.setGeometry(QtCore.QRect(0, 0, 701, 501))
        self.background1.setMinimumSize(QtCore.QSize(0, 0))
        self.background1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.background1.setText("")
        self.background1.setObjectName("background1")
        self.background1.raise_()
        self.continue1.raise_()
        self.cancle1.raise_()
        self.icon1.raise_()
        self.main_text.raise_()
        self.switcher.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.continue2 = QtWidgets.QPushButton(self.page_2)
        self.continue2.setEnabled(False)
        self.continue2.setGeometry(QtCore.QRect(410, 440, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Molodo-font")
        font.setPointSize(10)
        self.continue2.setFont(font)
        self.continue2.setStyleSheet("QPushButton {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding: 10px;\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: rgba(230, 230, 230, 230);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(200, 200, 200, 230);\n"
"}\n"
"QPushButton:enabled {\n"
"    background-color: rgba(255, 255, 255, 230);\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgba(130, 130, 130, 230);\n"
"}")
        self.continue2.setCheckable(False)
        self.continue2.setObjectName("continue2")
        self.background2 = QtWidgets.QLabel(self.page_2)
        self.background2.setEnabled(True)
        self.background2.setGeometry(QtCore.QRect(0, 0, 701, 501))
        self.background2.setMinimumSize(QtCore.QSize(0, 0))
        self.background2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.background2.setText("")
        self.background2.setObjectName("background2")
        self.icon2 = QtWidgets.QLabel(self.page_2)
        self.icon2.setGeometry(QtCore.QRect(600, 20, 91, 91))
        self.icon2.setStyleSheet("")
        self.icon2.setText("")
        self.icon2.setObjectName("icon2")
        self.main_text_2 = QtWidgets.QLabel(self.page_2)
        self.main_text_2.setGeometry(QtCore.QRect(10, 20, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Monomakh Unicode")
        font.setPointSize(10)
        font.setStrikeOut(False)
        self.main_text_2.setFont(font)
        self.main_text_2.setStyleSheet("QLabel {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding: 10px;\n"
"        border-radius: 20px;\n"
"    }")
        self.main_text_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.main_text_2.setWordWrap(True)
        self.main_text_2.setObjectName("main_text_2")
        self.cancle2 = QtWidgets.QPushButton(self.page_2)
        self.cancle2.setGeometry(QtCore.QRect(570, 440, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Molodo-font")
        font.setPointSize(10)
        self.cancle2.setFont(font)
        self.cancle2.setStyleSheet("QPushButton {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding: 10px;\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: rgba(230, 230, 230, 230);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(200, 200, 200, 230);\n"
"}")
        self.cancle2.setObjectName("cancle2")
        self.back1 = QtWidgets.QPushButton(self.page_2)
        self.back1.setGeometry(QtCore.QRect(290, 440, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Molodo-font")
        font.setPointSize(10)
        self.back1.setFont(font)
        self.back1.setStyleSheet("QPushButton {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding: 10px;\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: rgba(230, 230, 230, 230);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(200, 200, 200, 230);\n"
"}")
        self.back1.setObjectName("back1")
        self.textBrowser = QtWidgets.QTextBrowser(self.page_2)
        self.textBrowser.setGeometry(QtCore.QRect(20, 120, 671, 251))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("QTextBrowser {background-color: rgba(255, 255, 255, 230);\n"
"color: black;\n"
"\n"
"}")
        self.textBrowser.setObjectName("textBrowser")
        self.i_accept = QtWidgets.QRadioButton(self.page_2)
        self.i_accept.setGeometry(QtCore.QRect(30, 390, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.i_accept.setFont(font)
        self.i_accept.setObjectName("i_accept")
        self.i_decline = QtWidgets.QRadioButton(self.page_2)
        self.i_decline.setGeometry(QtCore.QRect(30, 410, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.i_decline.setFont(font)
        self.i_decline.setChecked(True)
        self.i_decline.setObjectName("i_decline")
        self.main_text_3 = QtWidgets.QLabel(self.page_2)
        self.main_text_3.setGeometry(QtCore.QRect(50, 80, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Monomakh Unicode")
        font.setPointSize(10)
        font.setStrikeOut(False)
        self.main_text_3.setFont(font)
        self.main_text_3.setStyleSheet("QLabel {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        border-radius: 10px;\n"
"    }")
        self.main_text_3.setAlignment(QtCore.Qt.AlignCenter)
        self.main_text_3.setWordWrap(True)
        self.main_text_3.setObjectName("main_text_3")
        self.back_accept = QtWidgets.QLabel(self.page_2)
        self.back_accept.setGeometry(QtCore.QRect(20, 380, 261, 61))
        self.back_accept.setStyleSheet("QLabel {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding: 10px;\n"
"        border-radius: 10px;\n"
"    }")
        self.back_accept.setText("")
        self.back_accept.setObjectName("back_accept")
        self.background2.raise_()
        self.back_accept.raise_()
        self.icon2.raise_()
        self.main_text_2.raise_()
        self.cancle2.raise_()
        self.continue2.raise_()
        self.back1.raise_()
        self.textBrowser.raise_()
        self.main_text_3.raise_()
        self.i_accept.raise_()
        self.i_decline.raise_()
        self.switcher.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.main_text_4 = QtWidgets.QLabel(self.page_3)
        self.main_text_4.setGeometry(QtCore.QRect(10, 20, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Monomakh Unicode")
        font.setPointSize(10)
        font.setStrikeOut(False)
        self.main_text_4.setFont(font)
        self.main_text_4.setStyleSheet("QLabel {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding: 10px;\n"
"        border-radius: 20px;\n"
"    }")
        self.main_text_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.main_text_4.setWordWrap(True)
        self.main_text_4.setObjectName("main_text_4")
        self.continue3 = QtWidgets.QPushButton(self.page_3)
        self.continue3.setGeometry(QtCore.QRect(410, 440, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Molodo-font")
        font.setPointSize(10)
        self.continue3.setFont(font)
        self.continue3.setStyleSheet("QPushButton {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding: 10px;\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: rgba(230, 230, 230, 230);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(200, 200, 200, 230);\n"
"}")
        self.continue3.setObjectName("continue3")
        self.main_text_5 = QtWidgets.QLabel(self.page_3)
        self.main_text_5.setGeometry(QtCore.QRect(50, 80, 551, 31))
        font = QtGui.QFont()
        font.setFamily("Monomakh Unicode")
        font.setPointSize(10)
        font.setStrikeOut(False)
        self.main_text_5.setFont(font)
        self.main_text_5.setStyleSheet("QLabel {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        border-radius: 10px;\n"
"    }")
        self.main_text_5.setAlignment(QtCore.Qt.AlignCenter)
        self.main_text_5.setWordWrap(True)
        self.main_text_5.setObjectName("main_text_5")
        self.back2 = QtWidgets.QPushButton(self.page_3)
        self.back2.setGeometry(QtCore.QRect(290, 440, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Molodo-font")
        font.setPointSize(10)
        self.back2.setFont(font)
        self.back2.setStyleSheet("QPushButton {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding: 10px;\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: rgba(230, 230, 230, 230);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(200, 200, 200, 230);\n"
"}")
        self.back2.setObjectName("back2")
        self.background3 = QtWidgets.QLabel(self.page_3)
        self.background3.setGeometry(QtCore.QRect(0, 0, 701, 501))
        self.background3.setMinimumSize(QtCore.QSize(0, 0))
        self.background3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.background3.setText("")
        self.background3.setObjectName("background3")
        self.cancle3 = QtWidgets.QPushButton(self.page_3)
        self.cancle3.setGeometry(QtCore.QRect(570, 440, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Molodo-font")
        font.setPointSize(10)
        self.cancle3.setFont(font)
        self.cancle3.setStyleSheet("QPushButton {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding: 10px;\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: rgba(230, 230, 230, 230);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(200, 200, 200, 230);\n"
"}")
        self.cancle3.setObjectName("cancle3")
        self.icon3 = QtWidgets.QLabel(self.page_3)
        self.icon3.setGeometry(QtCore.QRect(600, 20, 91, 91))
        self.icon3.setText("")
        self.icon3.setObjectName("icon3")
        self.project_path = QtWidgets.QLineEdit(self.page_3)
        self.project_path.setGeometry(QtCore.QRect(50, 120, 531, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.project_path.setFont(font)
        self.project_path.setStyleSheet("")
        self.project_path.setObjectName("project_path")
        self.view = QtWidgets.QPushButton(self.page_3)
        self.view.setGeometry(QtCore.QRect(590, 120, 93, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.view.setFont(font)
        self.view.setStyleSheet("QPushButton {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: rgba(230, 230, 230, 230);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(200, 200, 200, 230);\n"
"}")
        self.view.setObjectName("view")
        self.background3.raise_()
        self.main_text_4.raise_()
        self.continue3.raise_()
        self.main_text_5.raise_()
        self.back2.raise_()
        self.cancle3.raise_()
        self.icon3.raise_()
        self.project_path.raise_()
        self.view.raise_()
        self.switcher.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.continue4 = QtWidgets.QPushButton(self.page_4)
        self.continue4.setGeometry(QtCore.QRect(410, 440, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Molodo-font")
        font.setPointSize(10)
        self.continue4.setFont(font)
        self.continue4.setStyleSheet("QPushButton {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding: 10px;\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: rgba(230, 230, 230, 230);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(200, 200, 200, 230);\n"
"}")
        self.continue4.setObjectName("continue4")
        self.main_text_6 = QtWidgets.QLabel(self.page_4)
        self.main_text_6.setGeometry(QtCore.QRect(50, 80, 511, 31))
        font = QtGui.QFont()
        font.setFamily("Monomakh Unicode")
        font.setPointSize(8)
        font.setStrikeOut(False)
        self.main_text_6.setFont(font)
        self.main_text_6.setStyleSheet("QLabel {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        border-radius: 10px;\n"
"    }")
        self.main_text_6.setAlignment(QtCore.Qt.AlignCenter)
        self.main_text_6.setWordWrap(True)
        self.main_text_6.setObjectName("main_text_6")
        self.main_text_7 = QtWidgets.QLabel(self.page_4)
        self.main_text_7.setGeometry(QtCore.QRect(10, 20, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Monomakh Unicode")
        font.setPointSize(10)
        font.setStrikeOut(False)
        self.main_text_7.setFont(font)
        self.main_text_7.setStyleSheet("QLabel {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding: 10px;\n"
"        border-radius: 20px;\n"
"    }")
        self.main_text_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.main_text_7.setWordWrap(True)
        self.main_text_7.setObjectName("main_text_7")
        self.back3 = QtWidgets.QPushButton(self.page_4)
        self.back3.setGeometry(QtCore.QRect(290, 440, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Molodo-font")
        font.setPointSize(10)
        self.back3.setFont(font)
        self.back3.setStyleSheet("QPushButton {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding: 10px;\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: rgba(230, 230, 230, 230);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(200, 200, 200, 230);\n"
"}")
        self.back3.setObjectName("back3")
        self.cancle4 = QtWidgets.QPushButton(self.page_4)
        self.cancle4.setGeometry(QtCore.QRect(570, 440, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Molodo-font")
        font.setPointSize(10)
        self.cancle4.setFont(font)
        self.cancle4.setStyleSheet("QPushButton {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding: 10px;\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: rgba(230, 230, 230, 230);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(200, 200, 200, 230);\n"
"}")
        self.cancle4.setObjectName("cancle4")
        self.label = QtWidgets.QLabel(self.page_4)
        self.label.setGeometry(QtCore.QRect(20, 430, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding-left: 5px;\n"
"        border-radius: 5px;\n"
"    }")
        self.label.setObjectName("label")
        self.icon4 = QtWidgets.QLabel(self.page_4)
        self.icon4.setGeometry(QtCore.QRect(600, 20, 91, 91))
        self.icon4.setText("")
        self.icon4.setObjectName("icon4")
        self.background4 = QtWidgets.QLabel(self.page_4)
        self.background4.setGeometry(QtCore.QRect(0, 0, 701, 501))
        self.background4.setMinimumSize(QtCore.QSize(0, 0))
        self.background4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.background4.setText("")
        self.background4.setObjectName("background4")
        self.modules = QtWidgets.QTreeView(self.page_4)
        self.modules.setGeometry(QtCore.QRect(50, 120, 611, 301))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.modules.setFont(font)
        self.modules.setStyleSheet("QTreeView {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"    }\n"
"QTreeView::branch { border: none; }\n"
"QTreeView::item { border-bottom: none; }")
        self.modules.setEditTriggers(QtWidgets.QAbstractItemView.EditKeyPressed)
        self.modules.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.modules.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.modules.setExpandsOnDoubleClick(False)
        self.modules.setObjectName("modules")
        self.modules.header().setVisible(False)
        self.background4.raise_()
        self.continue4.raise_()
        self.main_text_6.raise_()
        self.main_text_7.raise_()
        self.back3.raise_()
        self.cancle4.raise_()
        self.label.raise_()
        self.icon4.raise_()
        self.modules.raise_()
        self.switcher.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.back4 = QtWidgets.QPushButton(self.page_5)
        self.back4.setGeometry(QtCore.QRect(290, 440, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Molodo-font")
        font.setPointSize(10)
        self.back4.setFont(font)
        self.back4.setStyleSheet("QPushButton {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding: 10px;\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: rgba(230, 230, 230, 230);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(200, 200, 200, 230);\n"
"}")
        self.back4.setObjectName("back4")
        self.continue5 = QtWidgets.QPushButton(self.page_5)
        self.continue5.setGeometry(QtCore.QRect(410, 440, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Molodo-font")
        font.setPointSize(10)
        self.continue5.setFont(font)
        self.continue5.setStyleSheet("QPushButton {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding: 10px;\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: rgba(230, 230, 230, 230);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(200, 200, 200, 230);\n"
"}")
        self.continue5.setObjectName("continue5")
        self.cancle5 = QtWidgets.QPushButton(self.page_5)
        self.cancle5.setGeometry(QtCore.QRect(570, 440, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Molodo-font")
        font.setPointSize(10)
        self.cancle5.setFont(font)
        self.cancle5.setStyleSheet("QPushButton {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding: 10px;\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: rgba(230, 230, 230, 230);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(200, 200, 200, 230);\n"
"}")
        self.cancle5.setObjectName("cancle5")
        self.background5 = QtWidgets.QLabel(self.page_5)
        self.background5.setGeometry(QtCore.QRect(0, 0, 701, 501))
        self.background5.setMinimumSize(QtCore.QSize(0, 0))
        self.background5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.background5.setText("")
        self.background5.setObjectName("background5")
        self.main_text_8 = QtWidgets.QLabel(self.page_5)
        self.main_text_8.setGeometry(QtCore.QRect(10, 20, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Monomakh Unicode")
        font.setPointSize(10)
        font.setStrikeOut(False)
        self.main_text_8.setFont(font)
        self.main_text_8.setStyleSheet("QLabel {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding: 10px;\n"
"        border-radius: 20px;\n"
"    }")
        self.main_text_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.main_text_8.setWordWrap(True)
        self.main_text_8.setObjectName("main_text_8")
        self.icon5 = QtWidgets.QLabel(self.page_5)
        self.icon5.setGeometry(QtCore.QRect(600, 20, 91, 91))
        self.icon5.setText("")
        self.icon5.setObjectName("icon5")
        self.main_text_9 = QtWidgets.QLabel(self.page_5)
        self.main_text_9.setGeometry(QtCore.QRect(50, 80, 381, 31))
        font = QtGui.QFont()
        font.setFamily("Monomakh Unicode")
        font.setPointSize(8)
        font.setStrikeOut(False)
        self.main_text_9.setFont(font)
        self.main_text_9.setStyleSheet("QLabel {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        border-radius: 10px;\n"
"    }")
        self.main_text_9.setAlignment(QtCore.Qt.AlignCenter)
        self.main_text_9.setWordWrap(True)
        self.main_text_9.setObjectName("main_text_9")
        self.checkBox_auto = QtWidgets.QCheckBox(self.page_5)
        self.checkBox_auto.setGeometry(QtCore.QRect(60, 140, 371, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_auto.setFont(font)
        self.checkBox_auto.setChecked(True)
        self.checkBox_auto.setObjectName("checkBox_auto")
        self.checkBox_table = QtWidgets.QCheckBox(self.page_5)
        self.checkBox_table.setEnabled(True)
        self.checkBox_table.setGeometry(QtCore.QRect(60, 170, 371, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_table.setFont(font)
        self.checkBox_table.setChecked(True)
        self.checkBox_table.setObjectName("checkBox_table")
        self.checkBox_pusk = QtWidgets.QCheckBox(self.page_5)
        self.checkBox_pusk.setEnabled(True)
        self.checkBox_pusk.setGeometry(QtCore.QRect(60, 200, 371, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_pusk.setFont(font)
        self.checkBox_pusk.setChecked(True)
        self.checkBox_pusk.setObjectName("checkBox_pusk")
        self.back_accept_2 = QtWidgets.QLabel(self.page_5)
        self.back_accept_2.setGeometry(QtCore.QRect(50, 130, 331, 101))
        self.back_accept_2.setStyleSheet("QLabel {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding: 10px;\n"
"        border-radius: 10px;\n"
"    }")
        self.back_accept_2.setText("")
        self.back_accept_2.setObjectName("back_accept_2")
        self.background5.raise_()
        self.back_accept_2.raise_()
        self.back4.raise_()
        self.continue5.raise_()
        self.cancle5.raise_()
        self.main_text_8.raise_()
        self.icon5.raise_()
        self.main_text_9.raise_()
        self.checkBox_auto.raise_()
        self.checkBox_table.raise_()
        self.checkBox_pusk.raise_()
        self.switcher.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.main_text_11 = QtWidgets.QLabel(self.page_6)
        self.main_text_11.setGeometry(QtCore.QRect(10, 20, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Monomakh Unicode")
        font.setPointSize(10)
        font.setStrikeOut(False)
        self.main_text_11.setFont(font)
        self.main_text_11.setStyleSheet("QLabel {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding: 10px;\n"
"        border-radius: 20px;\n"
"    }")
        self.main_text_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.main_text_11.setWordWrap(True)
        self.main_text_11.setObjectName("main_text_11")
        self.main_text_10 = QtWidgets.QLabel(self.page_6)
        self.main_text_10.setGeometry(QtCore.QRect(50, 80, 591, 51))
        font = QtGui.QFont()
        font.setFamily("Monomakh Unicode")
        font.setPointSize(9)
        font.setStrikeOut(False)
        self.main_text_10.setFont(font)
        self.main_text_10.setStyleSheet("QLabel {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding-left:10px;\n"
"        border-radius: 10px;\n"
"    }")
        self.main_text_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.main_text_10.setWordWrap(True)
        self.main_text_10.setObjectName("main_text_10")
        self.cancle6 = QtWidgets.QPushButton(self.page_6)
        self.cancle6.setGeometry(QtCore.QRect(570, 440, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Molodo-font")
        font.setPointSize(10)
        self.cancle6.setFont(font)
        self.cancle6.setStyleSheet("QPushButton {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding: 10px;\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: rgba(230, 230, 230, 230);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(200, 200, 200, 230);\n"
"}")
        self.cancle6.setObjectName("cancle6")
        self.install = QtWidgets.QPushButton(self.page_6)
        self.install.setGeometry(QtCore.QRect(410, 440, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Molodo-font")
        font.setPointSize(10)
        self.install.setFont(font)
        self.install.setStyleSheet("QPushButton {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding: 10px;\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: rgba(230, 230, 230, 230);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(200, 200, 200, 230);\n"
"}")
        self.install.setObjectName("install")
        self.back5 = QtWidgets.QPushButton(self.page_6)
        self.back5.setGeometry(QtCore.QRect(290, 440, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Molodo-font")
        font.setPointSize(10)
        self.back5.setFont(font)
        self.back5.setStyleSheet("QPushButton {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding: 10px;\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: rgba(230, 230, 230, 230);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(200, 200, 200, 230);\n"
"}")
        self.back5.setObjectName("back5")
        self.icon6 = QtWidgets.QLabel(self.page_6)
        self.icon6.setGeometry(QtCore.QRect(10, 400, 91, 91))
        self.icon6.setText("")
        self.icon6.setObjectName("icon6")
        self.background6 = QtWidgets.QLabel(self.page_6)
        self.background6.setGeometry(QtCore.QRect(0, 0, 701, 501))
        self.background6.setMinimumSize(QtCore.QSize(0, 0))
        self.background6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.background6.setText("")
        self.background6.setObjectName("background6")
        self.background6.raise_()
        self.main_text_11.raise_()
        self.main_text_10.raise_()
        self.cancle6.raise_()
        self.install.raise_()
        self.back5.raise_()
        self.icon6.raise_()
        self.switcher.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.main_text_13 = QtWidgets.QLabel(self.page_7)
        self.main_text_13.setGeometry(QtCore.QRect(10, 20, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Monomakh Unicode")
        font.setPointSize(10)
        font.setStrikeOut(False)
        self.main_text_13.setFont(font)
        self.main_text_13.setStyleSheet("QLabel {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding: 10px;\n"
"        border-radius: 20px;\n"
"    }")
        self.main_text_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.main_text_13.setWordWrap(True)
        self.main_text_13.setObjectName("main_text_13")
        self.main_text_12 = QtWidgets.QLabel(self.page_7)
        self.main_text_12.setGeometry(QtCore.QRect(50, 80, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Monomakh Unicode")
        font.setPointSize(9)
        font.setStrikeOut(False)
        self.main_text_12.setFont(font)
        self.main_text_12.setStyleSheet("QLabel {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding-left:10px;\n"
"        border-radius: 10px;\n"
"    }")
        self.main_text_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.main_text_12.setWordWrap(True)
        self.main_text_12.setObjectName("main_text_12")
        self.cancle_installation = QtWidgets.QPushButton(self.page_7)
        self.cancle_installation.setGeometry(QtCore.QRect(570, 440, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Molodo-font")
        font.setPointSize(10)
        self.cancle_installation.setFont(font)
        self.cancle_installation.setStyleSheet("QPushButton {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding: 10px;\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: rgba(230, 230, 230, 230);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(200, 200, 200, 230);\n"
"}")
        self.cancle_installation.setObjectName("cancle_installation")
        self.progress_install = QtWidgets.QProgressBar(self.page_7)
        self.progress_install.setGeometry(QtCore.QRect(50, 170, 611, 31))
        self.progress_install.setStyleSheet("QProgressBar {\n"
"                border: 3px solid #5C3A1E;\n"
"                text-align: center;\n"
"                font-size: 16px;\n"
"                font-weight: bold;\n"
"                color: #fff7d6;\n"
"                background: #3E2F1C;\n"
"            }\n"
"\n"
"            QProgressBar::chunk {\n"
"                background: #E09F3E;\n"
"\n"
"            }\n"
"")
        self.progress_install.setProperty("value", 0)
        self.progress_install.setTextVisible(False)
        self.progress_install.setObjectName("progress_install")
        self.status_label = QtWidgets.QLabel(self.page_7)
        self.status_label.setGeometry(QtCore.QRect(50, 130, 611, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.status_label.setFont(font)
        self.status_label.setStyleSheet("QLabel {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding-left: 5px;\n"
"        border-radius: 5px;\n"
"    }")
        self.status_label.setObjectName("status_label")
        self.background7 = QtWidgets.QLabel(self.page_7)
        self.background7.setGeometry(QtCore.QRect(0, 0, 701, 501))
        self.background7.setMinimumSize(QtCore.QSize(0, 0))
        self.background7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.background7.setText("")
        self.background7.setObjectName("background7")
        self.icon7 = QtWidgets.QLabel(self.page_7)
        self.icon7.setGeometry(QtCore.QRect(10, 400, 91, 91))
        self.icon7.setText("")
        self.icon7.setObjectName("icon7")
        self.background7.raise_()
        self.main_text_13.raise_()
        self.main_text_12.raise_()
        self.cancle_installation.raise_()
        self.progress_install.raise_()
        self.status_label.raise_()
        self.icon7.raise_()
        self.switcher.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.background8 = QtWidgets.QLabel(self.page_8)
        self.background8.setGeometry(QtCore.QRect(0, 0, 701, 501))
        self.background8.setMinimumSize(QtCore.QSize(0, 0))
        self.background8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.background8.setText("")
        self.background8.setObjectName("background8")
        self.main_text_24 = QtWidgets.QLabel(self.page_8)
        self.main_text_24.setGeometry(QtCore.QRect(50, 80, 611, 51))
        font = QtGui.QFont()
        font.setFamily("Monomakh Unicode")
        font.setPointSize(9)
        font.setStrikeOut(False)
        self.main_text_24.setFont(font)
        self.main_text_24.setStyleSheet("QLabel {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding-left:10px;\n"
"        border-radius: 10px;\n"
"    }")
        self.main_text_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.main_text_24.setWordWrap(True)
        self.main_text_24.setObjectName("main_text_24")
        self.icon8 = QtWidgets.QLabel(self.page_8)
        self.icon8.setGeometry(QtCore.QRect(10, 400, 91, 91))
        self.icon8.setText("")
        self.icon8.setObjectName("icon8")
        self.ready = QtWidgets.QPushButton(self.page_8)
        self.ready.setGeometry(QtCore.QRect(570, 440, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Molodo-font")
        font.setPointSize(10)
        self.ready.setFont(font)
        self.ready.setStyleSheet("QPushButton {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding: 10px;\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: rgba(230, 230, 230, 230);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(200, 200, 200, 230);\n"
"}")
        self.ready.setObjectName("ready")
        self.main_text_23 = QtWidgets.QLabel(self.page_8)
        self.main_text_23.setGeometry(QtCore.QRect(10, 20, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Monomakh Unicode")
        font.setPointSize(10)
        font.setStrikeOut(False)
        self.main_text_23.setFont(font)
        self.main_text_23.setStyleSheet("QLabel {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding: 10px;\n"
"        border-radius: 20px;\n"
"    }")
        self.main_text_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.main_text_23.setWordWrap(True)
        self.main_text_23.setObjectName("main_text_23")
        self.isLaunchPanel = QtWidgets.QCheckBox(self.page_8)
        self.isLaunchPanel.setGeometry(QtCore.QRect(50, 140, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.isLaunchPanel.setFont(font)
        self.isLaunchPanel.setStyleSheet("QCheckBox {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding-left:15px;\n"
"        border-radius: 10px;\n"
"    }")
        self.isLaunchPanel.setChecked(True)
        self.isLaunchPanel.setObjectName("isLaunchPanel")
        self.switcher.addWidget(self.page_8)

        self.retranslateUi(InstallerFirstStep)
        self.switcher.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(InstallerFirstStep)

    def retranslateUi(self, InstallerFirstStep):
        _translate = QtCore.QCoreApplication.translate
        InstallerFirstStep.setWindowTitle(_translate("InstallerFirstStep", "Да здравствует Пересвет Панель!"))
        self.continue1.setText(_translate("InstallerFirstStep", "ДАЛЕЕ"))
        self.cancle1.setText(_translate("InstallerFirstStep", "Отмена"))
        self.main_text.setText(_translate("InstallerFirstStep", "<html><head/><body><p><span style=\" color:#ff0000;\">Д</span>обры люди, примите наш поклон!</p><p>Сия программа нарекается Пересвет Панель, во имя упрощения трудов ваших в деле установки и служения веб-приложений.</p><p>Соизволите ли вы доверить нам настройку всего потребного — Nginx, Apache, PHP, хранилища данных и прочие инструменты? Под сводами сей панели воздвигнем крепость вашу серверную и приведём всё в надлежащий лад.</p><p>Вам остаётся лишь в путь ступить — кнопью «Установить» подтвердить своё намерение. Да исполнится воля ваша, и да будет крепок оплот вашего веб-хозяйства!</p><p>Нажмите <span style=\" font-weight:600;\">«Далее»</span> для продолжения установки, и да сопутствует вам удача в цифровых пределах!</p></body></html>"))
        self.continue2.setText(_translate("InstallerFirstStep", "ДАЛЕЕ"))
        self.main_text_2.setText(_translate("InstallerFirstStep", "<html><head/><body><p><span style=\" color:#ff0000;\">Л</span><span style=\" color:#000000;\">ицензионное соглашение</span></p></body></html>"))
        self.cancle2.setText(_translate("InstallerFirstStep", "Отмена"))
        self.back1.setText(_translate("InstallerFirstStep", "Назад"))
        self.textBrowser.setHtml(_translate("InstallerFirstStep", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Настоящая серверная панель «Пересвет Панель» (далее – «Программа») защищена законами и международными соглашениями об авторском праве. Исключительные права на использование данной Программы принадлежат её автору(ам).</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1.Использование и распространение</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Программа предоставляется бесплатно, без лицензионных отчислений, на неограниченный срок, но при условии соблюдения настоящих ограничений.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Разрешается использовать Программу для собственных нужд, а также устанавливать и запускать её на любых совместимых системах.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Копирование Программы разрешается только в личных целях и не должно противоречить настоящим условиям. Распространение на публичных ресурсах допускается лишь с письменного согласия правообладателя и при условии сохранения данного лицензионного соглашения в неизменном виде.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2. Патриотические условия</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Устанавливая Программу, вы подтверждаете свою поддержку и любовь к России, а также разделяете ценности патриотизма и уважения к её традициям и культуре.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Установка и использование Программы свидетельствует о том, что вы не имеете намерений применять её во вред интересам Российской Федерации.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3. Условия предоставления</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Программа распространяется «как есть» без каких-либо гарантий, прямо выраженных или подразумеваемых, включая, но не ограничиваясь, гарантиями товарной пригодности или соответствия определённой цели.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Правообладатель не гарантирует непрерывность, безошибочность и полноту работы Программы.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">4. Ограничение ответственности</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ни при каких обстоятельствах правообладатель не несёт ответственность за любой ущерб (прямой, косвенный, случайный, специальный, штрафной и/или сопутствующий), а также убытки, возникшие в результате использования или невозможности использования Программы.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Это включает, но не ограничивается, упущенной выгодой, потерей данных, ущербом репутации или любым иным косвенным ущербом.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">5. Сторонние компоненты</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Положения настоящего лицензионного соглашения и авторские права не распространяются на программы и компоненты третьих лиц, которые могут поставляться вместе с дистрибутивом Программы. Условия использования таких компонентов регулируются лицензионными соглашениями соответствующих правообладателей.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">6. Прочие условия</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Использование Программы означает безоговорочное принятие всех положений настоящего соглашения.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Настоящее соглашение регулируется применимым законодательством и не ограничивает никаких прав, гарантированных законом.</p></body></html>"))
        self.i_accept.setText(_translate("InstallerFirstStep", "Я принимаю условия соглашения"))
        self.i_decline.setText(_translate("InstallerFirstStep", "Я не принимаю условия соглашения"))
        self.main_text_3.setText(_translate("InstallerFirstStep", "<html><head/><body><p>Молвь сию внемли, прежде нежели путь продолжишь!</p></body></html>"))
        self.main_text_4.setText(_translate("InstallerFirstStep", "<html><head/><body><p><span style=\" color:#ff0000;\">В</span><span style=\" color:#000000;\">ыбор папки установки</span></p></body></html>"))
        self.continue3.setText(_translate("InstallerFirstStep", "ДАЛЕЕ"))
        self.main_text_5.setText(_translate("InstallerFirstStep", "<html><head/><body><p>Добрый воин! Скажи, в кои палаты желаешь возвести Пересвет Панель?</p></body></html>"))
        self.back2.setText(_translate("InstallerFirstStep", "Назад"))
        self.cancle3.setText(_translate("InstallerFirstStep", "Отмена"))
        self.project_path.setText(_translate("InstallerFirstStep", "C:\\PeresvetPanel"))
        self.view.setText(_translate("InstallerFirstStep", "Обзор..."))
        self.continue4.setText(_translate("InstallerFirstStep", "ДАЛЕЕ"))
        self.main_text_6.setText(_translate("InstallerFirstStep", "<html><head/><body><p><span style=\" font-size:10pt;\">Изволь избрати, какие орудия серверного дела желаешь поставить</span></p></body></html>"))
        self.main_text_7.setText(_translate("InstallerFirstStep", "<html><head/><body><p><span style=\" color:#ff0000;\">В</span><span style=\" color:#000000;\">ыбор модулей</span></p></body></html>"))
        self.back3.setText(_translate("InstallerFirstStep", "Назад"))
        self.cancle4.setText(_translate("InstallerFirstStep", "Отмена"))
        self.label.setText(_translate("InstallerFirstStep", "Вес кладовых файлов:"))
        self.back4.setText(_translate("InstallerFirstStep", "Назад"))
        self.continue5.setText(_translate("InstallerFirstStep", "Далее"))
        self.cancle5.setText(_translate("InstallerFirstStep", "Отмена"))
        self.main_text_8.setText(_translate("InstallerFirstStep", "<html><head/><body><p><span style=\" color:#ff0000;\">Д</span><span style=\" color:#000000;\">ополнительные параметры</span></p></body></html>"))
        self.main_text_9.setText(_translate("InstallerFirstStep", "<html><head/><body><p><span style=\" font-size:10pt;\">Здесь можешь наречь тонкие уставы установки</span></p></body></html>"))
        self.checkBox_auto.setText(_translate("InstallerFirstStep", "Автоматический запуск при загрузке Windows"))
        self.checkBox_table.setText(_translate("InstallerFirstStep", "Создать значок на Рабочем столе"))
        self.checkBox_pusk.setText(_translate("InstallerFirstStep", "Добавить в меню \"Пуск\""))
        self.main_text_11.setText(_translate("InstallerFirstStep", "<html><head/><body><p><span style=\" color:#ff0000;\">В</span><span style=\" color:#000000;\">сё готово к установке</span></p></body></html>"))
        self.main_text_10.setText(_translate("InstallerFirstStep", "<html><head/><body><p><span style=\" font-size:10pt;\">Нажми </span><span style=\" font-size:10pt; font-weight:600;\">«Установить»</span><span style=\" font-size:10pt;\">, и Пересвет Панель воздвигнется в указанном тобой чертоге, готовая к службе и ратному делу веб-хозяйства!</span></p></body></html>"))
        self.cancle6.setText(_translate("InstallerFirstStep", "Отмена"))
        self.install.setText(_translate("InstallerFirstStep", "Установить"))
        self.back5.setText(_translate("InstallerFirstStep", "Назад"))
        self.main_text_13.setText(_translate("InstallerFirstStep", "<html><head/><body><p><span style=\" color:#ff0000;\">И</span><span style=\" color:#000000;\">дёт устновка</span></p></body></html>"))
        self.main_text_12.setText(_translate("InstallerFirstStep", "<html><head/><body><p><span style=\" font-size:10pt;\">Пересвет Панель ведёт установку вашего сервера</span></p></body></html>"))
        self.cancle_installation.setText(_translate("InstallerFirstStep", "Отмена"))
        self.status_label.setText(_translate("InstallerFirstStep", "Установка..."))
        self.main_text_24.setText(_translate("InstallerFirstStep", "<html><head/><body><p><span style=\" font-size:10pt;\">Се, Пересветъ-Понель нынѣ на числителѣ твоемъ! Готова она служити исправно, а вебъ-хозяйство и хранилища данных устроены во славу труда твоего.</span></p></body></html>"))
        self.ready.setText(_translate("InstallerFirstStep", "Готово"))
        self.main_text_23.setText(_translate("InstallerFirstStep", "<html><head/><body><p><span style=\" color:#ff0000;\">У</span><span style=\" color:#000000;\">становка завершена!</span></p></body></html>"))
        self.isLaunchPanel.setText(_translate("InstallerFirstStep", "Запустить панель"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    InstallerFirstStep = QtWidgets.QWidget()
    ui = Ui_InstallerFirstStep()
    ui.setupUi(InstallerFirstStep)
    InstallerFirstStep.show()
    sys.exit(app.exec_())
