# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'peresvet.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Peresvet(object):
    def setupUi(self, Peresvet):
        Peresvet.setObjectName("Peresvet")
        Peresvet.resize(700, 500)
        Peresvet.setMinimumSize(QtCore.QSize(700, 500))
        Peresvet.setMaximumSize(QtCore.QSize(700, 500))
        Peresvet.setStyleSheet("")
        self.tabWidget = QtWidgets.QTabWidget(Peresvet)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 701, 501))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.run_me = QtWidgets.QPushButton(self.tab)
        self.run_me.setGeometry(QtCore.QRect(20, 410, 91, 41))
        self.run_me.setStyleSheet("background: rgba(0, 255, 0, 120);\n"
"border: 2px solid black;\n"
"")
        self.run_me.setObjectName("run_me")
        self.checkBox = QtWidgets.QCheckBox(self.tab)
        self.checkBox.setGeometry(QtCore.QRect(540, 10, 141, 41))
        self.checkBox.setStyleSheet(" background-color: rgba(255, 255, 255, 230); color: black;\n"
" padding: 10px;\n"
"border-radius: 10px;")
        self.checkBox.setObjectName("checkBox")
        self.restart_me = QtWidgets.QPushButton(self.tab)
        self.restart_me.setGeometry(QtCore.QRect(140, 410, 93, 41))
        self.restart_me.setStyleSheet("background: rgba(255, 255, 0, 120);\n"
"border: 2px solid black;\n"
"")
        self.restart_me.setObjectName("restart_me")
        self.stop_me = QtWidgets.QPushButton(self.tab)
        self.stop_me.setGeometry(QtCore.QRect(260, 410, 93, 41))
        self.stop_me.setStyleSheet("background: rgba(255, 0, 0, 120);\n"
"border: 2px solid black;\n"
"")
        self.stop_me.setObjectName("stop_me")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 70, 91, 41))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        border: 2px solid black;\n"
"        padding: 10px;\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: rgba(230, 230, 230, 230);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(200, 200, 200, 230);\n"
"}\n"
"QLabel {\n"
"background-color: rgba(255, 255, 255, 230);\n"
"color: black;\n"
"padding-left: 5px;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 240, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Molodo-font")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-radius: 10px;")
        self.label_2.setObjectName("label_2")
        self.open_adminer = QtWidgets.QPushButton(self.tab)
        self.open_adminer.setGeometry(QtCore.QRect(20, 290, 93, 41))
        self.open_adminer.setStyleSheet("QPushButton {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding: 10px;\n"
"        border: 2px solid black;\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: rgba(230, 230, 230, 230);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(200, 200, 200, 230);\n"
"}\n"
"QPushButton:enabled {\n"
"    background-color: rgba(255, 255, 255, 230);\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgba(130, 130, 130, 230);\n"
"}")
        self.open_adminer.setObjectName("open_adminer")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 130, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Molodo-font")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("border-radius: 10px;")
        self.label.setObjectName("label")
        self.open_phpmyadmin = QtWidgets.QPushButton(self.tab)
        self.open_phpmyadmin.setGeometry(QtCore.QRect(20, 180, 93, 41))
        self.open_phpmyadmin.setStyleSheet("QPushButton {\n"
"        background-color: rgba(255, 255, 255, 230);\n"
"        color: black;\n"
"        padding: 10px;\n"
"        border: 2px solid black;\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: rgba(230, 230, 230, 230);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(200, 200, 200, 230);\n"
"}\n"
"QPushButton:enabled {\n"
"    background-color: rgba(255, 255, 255, 230);\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgba(130, 130, 130, 230);\n"
"}")
        self.open_phpmyadmin.setObjectName("open_phpmyadmin")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(20, 20, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Molodo-font")
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("border-radius: 10px;")
        self.label_9.setObjectName("label_9")
        self.icon1 = QtWidgets.QLabel(self.tab)
        self.icon1.setGeometry(QtCore.QRect(590, 370, 91, 91))
        self.icon1.setText("")
        self.icon1.setObjectName("icon1")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border-radius: 3px;")
        self.label_3.setObjectName("label_3")
        self.apache_list = QtWidgets.QComboBox(self.tab_2)
        self.apache_list.setGeometry(QtCore.QRect(30, 70, 201, 25))
        self.apache_list.setObjectName("apache_list")
        self.nginx_list = QtWidgets.QComboBox(self.tab_2)
        self.nginx_list.setGeometry(QtCore.QRect(30, 120, 201, 25))
        self.nginx_list.setObjectName("nginx_list")
        self.php_list = QtWidgets.QComboBox(self.tab_2)
        self.php_list.setGeometry(QtCore.QRect(30, 170, 201, 25))
        self.php_list.setObjectName("php_list")
        self.postgresql_list = QtWidgets.QComboBox(self.tab_2)
        self.postgresql_list.setGeometry(QtCore.QRect(30, 270, 201, 25))
        self.postgresql_list.setObjectName("postgresql_list")
        self.mysql_list = QtWidgets.QComboBox(self.tab_2)
        self.mysql_list.setGeometry(QtCore.QRect(30, 320, 201, 25))
        self.mysql_list.setObjectName("mysql_list")
        self.redis_list = QtWidgets.QComboBox(self.tab_2)
        self.redis_list.setGeometry(QtCore.QRect(30, 370, 201, 25))
        self.redis_list.setObjectName("redis_list")
        self.server_type = QtWidgets.QLabel(self.tab_2)
        self.server_type.setGeometry(QtCore.QRect(150, 20, 201, 21))
        self.server_type.setStyleSheet("border-radius: 3px;")
        self.server_type.setObjectName("server_type")
        self.apache_checkbox = QtWidgets.QCheckBox(self.tab_2)
        self.apache_checkbox.setGeometry(QtCore.QRect(240, 70, 121, 25))
        self.apache_checkbox.setStyleSheet("QCheckBox::indicator {\n"
"    width:  25px;\n"
"    height: 25px;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    image: url(images/checkbox_active.png);\n"
"}\n"
"QCheckBox::indicator:unchecked  {\n"
"    image: url(images/checkbox_deactive.png);\n"
"}\n"
"QCheckBox::indicator:disabled  {\n"
"    image: url(images/checkbox_disabled.png);\n"
"}")
        self.apache_checkbox.setText("")
        self.apache_checkbox.setObjectName("apache_checkbox")
        self.nginx_checkbox = QtWidgets.QCheckBox(self.tab_2)
        self.nginx_checkbox.setGeometry(QtCore.QRect(240, 120, 121, 25))
        self.nginx_checkbox.setStyleSheet("QCheckBox::indicator {\n"
"    width:  25px;\n"
"    height: 25px;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    image: url(images/checkbox_active.png);\n"
"}\n"
"QCheckBox::indicator:unchecked  {\n"
"    image: url(images/checkbox_deactive.png);\n"
"}\n"
"QCheckBox::indicator:disabled  {\n"
"    image: url(images/checkbox_disabled.png);\n"
"}")
        self.nginx_checkbox.setText("")
        self.nginx_checkbox.setObjectName("nginx_checkbox")
        self.postgresql_checkbox = QtWidgets.QCheckBox(self.tab_2)
        self.postgresql_checkbox.setGeometry(QtCore.QRect(240, 270, 121, 25))
        self.postgresql_checkbox.setStyleSheet("QCheckBox::indicator {\n"
"    width:  25px;\n"
"    height: 25px;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    image: url(images/checkbox_active.png);\n"
"}\n"
"QCheckBox::indicator:unchecked  {\n"
"    image: url(images/checkbox_deactive.png);\n"
"}\n"
"QCheckBox::indicator:disabled  {\n"
"    image: url(images/checkbox_disabled.png);\n"
"}")
        self.postgresql_checkbox.setText("")
        self.postgresql_checkbox.setObjectName("postgresql_checkbox")
        self.mysql_checkbox = QtWidgets.QCheckBox(self.tab_2)
        self.mysql_checkbox.setGeometry(QtCore.QRect(240, 320, 121, 25))
        self.mysql_checkbox.setStyleSheet("QCheckBox::indicator {\n"
"    width:  25px;\n"
"    height: 25px;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    image: url(images/checkbox_active.png);\n"
"}\n"
"QCheckBox::indicator:unchecked  {\n"
"    image: url(images/checkbox_deactive.png);\n"
"}\n"
"QCheckBox::indicator:disabled  {\n"
"    image: url(images/checkbox_disabled.png);\n"
"}")
        self.mysql_checkbox.setText("")
        self.mysql_checkbox.setObjectName("mysql_checkbox")
        self.redis_checkbox = QtWidgets.QCheckBox(self.tab_2)
        self.redis_checkbox.setGeometry(QtCore.QRect(240, 370, 121, 25))
        self.redis_checkbox.setStyleSheet("QCheckBox::indicator {\n"
"    width:  25px;\n"
"    height: 25px;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    image: url(images/checkbox_active.png);\n"
"}\n"
"QCheckBox::indicator:unchecked  {\n"
"    image: url(images/checkbox_deactive.png);\n"
"}\n"
"QCheckBox::indicator:disabled  {\n"
"    image: url(images/checkbox_disabled.png);\n"
"}")
        self.redis_checkbox.setText("")
        self.redis_checkbox.setObjectName("redis_checkbox")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(30, 150, 201, 21))
        self.label_10.setStyleSheet("border-radius: 3px;")
        self.label_10.setObjectName("label_10")
        self.icon2 = QtWidgets.QLabel(self.tab_2)
        self.icon2.setGeometry(QtCore.QRect(590, 370, 91, 91))
        self.icon2.setText("")
        self.icon2.setObjectName("icon2")
        self.server_type_2 = QtWidgets.QLabel(self.tab_2)
        self.server_type_2.setGeometry(QtCore.QRect(30, 50, 201, 21))
        self.server_type_2.setStyleSheet("border-radius: 3px;")
        self.server_type_2.setObjectName("server_type_2")
        self.server_type_3 = QtWidgets.QLabel(self.tab_2)
        self.server_type_3.setGeometry(QtCore.QRect(30, 100, 201, 21))
        self.server_type_3.setStyleSheet("border-radius: 3px;")
        self.server_type_3.setObjectName("server_type_3")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(10, 220, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("border-radius: 3px;")
        self.label_8.setObjectName("label_8")
        self.server_type_4 = QtWidgets.QLabel(self.tab_2)
        self.server_type_4.setGeometry(QtCore.QRect(30, 250, 201, 21))
        self.server_type_4.setStyleSheet("border-radius: 3px;")
        self.server_type_4.setObjectName("server_type_4")
        self.server_type_5 = QtWidgets.QLabel(self.tab_2)
        self.server_type_5.setGeometry(QtCore.QRect(30, 300, 201, 21))
        self.server_type_5.setStyleSheet("border-radius: 3px;")
        self.server_type_5.setObjectName("server_type_5")
        self.server_type_6 = QtWidgets.QLabel(self.tab_2)
        self.server_type_6.setGeometry(QtCore.QRect(30, 350, 201, 21))
        self.server_type_6.setStyleSheet("border-radius: 3px;")
        self.server_type_6.setObjectName("server_type_6")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Peresvet)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Peresvet)

    def retranslateUi(self, Peresvet):
        _translate = QtCore.QCoreApplication.translate
        Peresvet.setWindowTitle(_translate("Peresvet", "Пересвет Панель"))
        self.run_me.setText(_translate("Peresvet", "Запуск"))
        self.checkBox.setText(_translate("Peresvet", "Автозапуск"))
        self.restart_me.setText(_translate("Peresvet", "Перезапуск"))
        self.stop_me.setText(_translate("Peresvet", "Остановить"))
        self.pushButton_6.setText(_translate("Peresvet", "Открыть"))
        self.label_2.setText(_translate("Peresvet", "ADMINER"))
        self.open_adminer.setText(_translate("Peresvet", "Открыть"))
        self.label.setText(_translate("Peresvet", "phpMyAdmin"))
        self.open_phpmyadmin.setText(_translate("Peresvet", "Открыть"))
        self.label_9.setText(_translate("Peresvet", "Проекты"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Peresvet", "Главная"))
        self.label_3.setText(_translate("Peresvet", "Веб-серверы"))
        self.server_type.setText(_translate("Peresvet", "Выключено"))
        self.label_10.setText(_translate("Peresvet", "PHP"))
        self.server_type_2.setText(_translate("Peresvet", "apache"))
        self.server_type_3.setText(_translate("Peresvet", "nginx"))
        self.label_8.setText(_translate("Peresvet", "Базы данных"))
        self.server_type_4.setText(_translate("Peresvet", "postgresql"))
        self.server_type_5.setText(_translate("Peresvet", "mysql"))
        self.server_type_6.setText(_translate("Peresvet", "redis"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Peresvet", "Настройки модулей"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Peresvet = QtWidgets.QWidget()
    ui = Ui_Peresvet()
    ui.setupUi(Peresvet)
    Peresvet.show()
    sys.exit(app.exec_())
